export const products = {
  "Popular products": [
    {
      id: 1,
      title: "PlayStation 5",
      category: "PlayStation Consoles",
      price: "$800.00",
      rating: 5,
      image: "/assets/images/apple-ipad-w-silver-1.jpg",
      image2: "/assets/images/apple-ipad-w-silver-2-212x242.jpg",
    },
    {
      id: 2,
      title: "Apple Watch Series 8",
      category: "Smart Watches",
      price: "$399.00",
      discount: "-10%",
      rating: 4.5,
      image: "/assets/images/apple-ipad-w-silver-1.jpg",
      image2: "/assets/images/apple-ipad-w-silver-2-212x242.jpg",
    },
    {
      id: 3,
      title: "Apple iPhone 14 Plus",
      category: "iPhone",
      price: "$899.00",
      sale: "$799.00",
      rating: 4.5,
      hot: true,
      image: "/assets/images/apple-ipad-w-silver-1.jpg",
      image2: "/assets/images/apple-ipad-w-silver-2-212x242.jpg",
    },
    {
      id: 4,
      title: "Apple iPhone 14 Plus",
      category: "iPhone",
      price: "$899.00",
      sale: "$799.00",
      rating: 4.5,
      hot: true,
      image: "/assets/images/apple-ipad-w-silver-1.jpg",
      image2: "/assets/images/apple-ipad-w-silver-2-212x242.jpg",
    },
    {
      id: 5,
      title: "Apple iPhone 14 Plus",
      category: "iPhone",
      price: "$899.00",
      sale: "$799.00",
      rating: 4.5,
      hot: true,
      image: "/assets/images/apple-ipad-w-silver-1.jpg",
      image2: "/assets/images/apple-ipad-w-silver-2-212x242.jpg",
    },
    {
      id: 6,
      title: "Apple iPhone 14 Plus",
      category: "iPhone",
      price: "$899.00",
      sale: "$799.00",
      rating: 4.5,
      discount: "-10%",
      hot: true,
      image: "/assets/images/apple-ipad-w-silver-1.jpg",
      image2: "/assets/images/apple-ipad-w-silver-2-212x242.jpg",
    },
    {
      id: 7,
      title: "Apple iPhone 14 Plus",
      category: "iPhone",
      price: "$899.00",
      sale: "$799.00",
      rating: 4.5,
      hot: true,
      image: "/assets/images/apple-ipad-w-silver-1.jpg",
      image2: "/assets/images/apple-ipad-w-silver-2-212x242.jpg",
    },
    {
      id: 8,
      title: "Apple iPhone 14 Plus",
      category: "iPhone",
      price: "$899.00",
      sale: "$799.00",
      rating: 4.5,
      hot: true,
      image: "/assets/images/apple-ipad-w-silver-1.jpg",
      image2: "/assets/images/apple-ipad-w-silver-2-212x242.jpg",
    },
    {
      id: 9,
      title: "Apple iPhone 14 Plus",
      category: "iPhone",
      price: "$899.00",
      sale: "$799.00",
      rating: 4.5,
      hot: true,
      image: "/assets/images/apple-ipad-w-silver-1.jpg",
      image2: "/assets/images/apple-ipad-w-silver-2-212x242.jpg",
    },
    {
      id: 10,
      title: "Apple iPhone 14 Plus",
      category: "iPhone",
      price: "$899.00",
      sale: "$799.00",
      rating: 4.5,
      hot: true,
      image: "/assets/images/apple-ipad-w-silver-1.jpg",
      image2: "/assets/images/apple-ipad-w-silver-2-212x242.jpg",
    },
  ],
  "Most-viewed products": [
    {
      id: 1,
      title: "HP Victus 16-e0174nw",
      category: "Gaming Laptop",
      price: "$950.00",
      rating: 4,
      hot: true,
      discount: "-10%",
      image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
      image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
    },
    {
      id: 2,
      title: "ASUS ROG Strix G17",
      category: "Gaming Laptop",
      price: "$1,300.00",
      rating: 5,
      discount: "-20%",
      image: "/assets/images/apple-ipad-w-silver-1.jpg",
      image2: "/assets/images/apple-ipad-w-silver-2-212x242.jpg",
    },
    {
      id: 3,
      title: "ASUS ROG Strix G17",
      category: "Gaming Laptop",
      price: "$1,300.00",
      rating: 5,
      discount: "-20%",
      image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
      image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
    },
    {
      id: 4,
      title: "ASUS ROG Strix G17",
      category: "Gaming Laptop",
      price: "$1,300.00",
      rating: 5,
      discount: "-20%",
      image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
      image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
    },
    {
      id: 5,
      title: "ASUS ROG Strix G17",
      category: "Gaming Laptop",
      price: "$1,300.00",
      rating: 5,
      discount: "-20%",
      image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
      image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
    },
    {
      id: 6,
      title: "ASUS ROG Strix G17",
      category: "Gaming Laptop",
      price: "$1,300.00",
      rating: 5,
      discount: "-20%",
      image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
      image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
    },
    {
      id: 7,
      title: "ASUS ROG Strix G17",
      category: "Gaming Laptop",
      price: "$1,300.00",
      rating: 5,
      discount: "-20%",
      image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
      image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
    },
    {
      id: 8,
      title: "ASUS ROG Strix G17",
      category: "Gaming Laptop",
      price: "$1,300.00",
      rating: 5,
      discount: "-20%",
      image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
      image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
    },
    {
      id: 9,
      title: "ASUS ROG Strix G17",
      category: "Gaming Laptop",
      price: "$1,300.00",
      rating: 5,
      discount: "-20%",
      image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
      image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
    },
    {
      id: 10,
      title: "ASUS ROG Strix G17",
      category: "Gaming Laptop",
      price: "$1,300.00",
      rating: 5,
      discount: "-20%",
      image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
      image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
    },
  ],
  "Top selling": [
    {
      id: 1,
      title: "Apple Mac mini M1",
      category: "Office PCs",
      price: "$699.00",
      rating: 4,
      image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
      image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
    },
    {
      id: 2,
      title: "Apple Mac mini M1",
      category: "Office PCs",
      price: "$699.00",
      rating: 4,
      image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
      image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
    },
    {
      id: 3,
      title: "Apple iPad Wi-Fi",
      category: "Apple Ipad",
      price: "$450.00",
      rating: 4.5,
      image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
      image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
    },
    {
      id: 4,
      title: "Apple Mac mini M1",
      category: "Office PCs",
      price: "$699.00",
      rating: 4,
      image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
      image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
    },
    {
      id: 5,
      title: "Apple Mac mini M1",
      category: "Office PCs",
      price: "$699.00",
      rating: 4,
      image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
      image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
    },
    {
      id: 6,
      title: "Apple Mac mini M1",
      category: "Office PCs",
      price: "$699.00",
      rating: 4,
      image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
      image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
    },
    {
      id: 7,
      title: "Apple Mac mini M1",
      category: "Office PCs",
      price: "$699.00",
      rating: 4,
      image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
      image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
    },
    {
      id: 8,
      title: "Apple Mac mini M1",
      category: "Office PCs",
      price: "$699.00",
      rating: 4,
      image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
      image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
    },
    {
      id: 9,
      title: "Apple Mac mini M1",
      category: "Office PCs",
      price: "$699.00",
      rating: 4,
      image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
      image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
    },
  ],
};
