export const products = [
  {
    id: 1,
    title: "PlayStation 5",
    category: "PlayStation Consoles",
    price: "$800.00",
    rating: 5,
    image: "/assets/images/apple-ipad-w-silver-1.jpg",
    image2: "/assets/images/apple-ipad-w-silver-2-212x242.jpg",
    tab: "Popular products",
    dsc: "Experience the ultimate viewing experience on the iPhone 14 Plus. With its large 6.7-inch Super Retina XDR display, powerful A15 Bionic chip, and advanced camera system, you can capture stunning photos and videos, play demanding games, and stay connected all day long.",
  },
  {
    id: 2,
    title: "Apple Watch Series 8",
    category: "Smart Watches",
    price: "$399.00",
    discount: "-10%",
    rating: 4.5,
    dsc: "Experience the ultimate viewing experience on the iPhone 14 Plus. With its large 6.7-inch Super Retina XDR display, powerful A15 Bionic chip, and advanced camera system, you can capture stunning photos and videos, play demanding games, and stay connected all day long.",
    tab: "Popular products",
    image: "/assets/images/apple-ipad-w-silver-1.jpg",
    image2: "/assets/images/apple-ipad-w-silver-2-212x242.jpg",
  },
  {
    id: 3,
    title: "Apple iPhone 14 Plus",
    category: "iPhone",
    price: "$899.00",
    sale: "$799.00",
    rating: 4.5,
    tab: "Popular products",
    hot: true,
    image: "/assets/images/apple-ipad-w-silver-1.jpg",
    image2: "/assets/images/apple-ipad-w-silver-2-212x242.jpg",
  },
  {
    id: 4,
    tab: "Popular products",
    title: "Apple iPhone 14 Plus",
    category: "iPhone",
    price: "$899.00",
    sale: "$799.00",
    rating: 4.5,
    hot: true,
    image: "/assets/images/apple-ipad-w-silver-1.jpg",
    image2: "/assets/images/apple-ipad-w-silver-2-212x242.jpg",
  },
  {
    id: 5,
    title: "Apple iPhone 14 Plus",
    category: "iPhone",
    price: "$899.00",
    tab: "Popular products",
    sale: "$799.00",
    rating: 4.5,
    hot: true,
    image: "/assets/images/apple-ipad-w-silver-1.jpg",
    image2: "/assets/images/apple-ipad-w-silver-2-212x242.jpg",
  },
  {
    id: 6,
    title: "Apple iPhone 14 Plus",
    category: "iPhone",
    price: "$899.00",
    sale: "$799.00",
    rating: 4.5,
    tab: "Popular products",
    discount: "-10%",
    hot: true,
    image: "/assets/images/apple-ipad-w-silver-1.jpg",
    image2: "/assets/images/apple-ipad-w-silver-2-212x242.jpg",
  },
  {
    id: 7,
    title: "Apple iPhone 14 Plus",
    category: "iPhone",
    price: "$899.00",
    sale: "$799.00",
    tab: "Popular products",
    rating: 4.5,
    hot: true,
    image: "/assets/images/apple-ipad-w-silver-1.jpg",
    image2: "/assets/images/apple-ipad-w-silver-2-212x242.jpg",
  },
  {
    id: 8,
    title: "Apple iPhone 14 Plus",
    category: "iPhone",
    price: "$899.00",
    tab: "Popular products",
    sale: "$799.00",
    rating: 4.5,
    hot: true,
    image: "/assets/images/apple-ipad-w-silver-1.jpg",
    image2: "/assets/images/apple-ipad-w-silver-2-212x242.jpg",
  },
  {
    id: 9,
    title: "Apple iPhone 14 Plus",
    category: "iPhone",
    price: "$899.00",
    sale: "$799.00",
    tab: "Popular products",
    rating: 4.5,
    hot: true,
    image: "/assets/images/apple-ipad-w-silver-1.jpg",
    image2: "/assets/images/apple-ipad-w-silver-2-212x242.jpg",
  },
  {
    id: 10,
    title: "Apple iPhone 14 Plus",
    category: "iPhone",
    price: "$899.00",
    tab: "Popular products",
    sale: "$799.00",
    rating: 4.5,
    hot: true,
    image: "/assets/images/apple-ipad-w-silver-1.jpg",
    image2: "/assets/images/apple-ipad-w-silver-2-212x242.jpg",
  },

  {
    id: 11,
    title: "HP Victus 16-e0174nw",
    category: "Gaming Laptop",
    price: "$950.00",
    rating: 4,
    hot: true,
    tab: "Popular products",
    discount: "-10%",
    image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
    image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
  },
  {
    id: 12,
    title: "ASUS ROG Strix G17",
    category: "Gaming Laptop",
    price: "$1,300.00",
    rating: 5,
    tab: "Most-viewed products",
    discount: "-20%",
    image: "/assets/images/apple-ipad-w-silver-1.jpg",
    image2: "/assets/images/apple-ipad-w-silver-2-212x242.jpg",
  },
  {
    id: 13,
    title: "ASUS ROG Strix G17",
    category: "Gaming Laptop",
    rating: 5,
    tab: "Most-viewed products",

    price: "$1,300.00",
    rating: 5,
    discount: "-20%",
    image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
    image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
  },
  {
    id: 14,
    title: "ASUS ROG Strix G17",
    category: "Gaming Laptop",
    price: "$1,300.00",
    rating: 5,
    tab: "Most-viewed products",

    rating: 5,
    discount: "-20%",
    image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
    image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
  },
  {
    id: 15,
    title: "ASUS ROG Strix G17",
    category: "Gaming Laptop",
    rating: 5,
    tab: "Most-viewed products",

    price: "$1,300.00",
    rating: 5,
    discount: "-20%",
    image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
    image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
  },
  {
    id: 16,
    title: "ASUS ROG Strix G17",
    category: "Gaming Laptop",
    price: "$1,300.00",
    rating: 5,
    rating: 5,
    tab: "Most-viewed products",

    discount: "-20%",
    image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
    image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
  },
  {
    id: 17,
    title: "ASUS ROG Strix G17",
    category: "Gaming Laptop",
    price: "$1,300.00",
    rating: 5,
    tab: "Most-viewed products",

    rating: 5,
    discount: "-20%",
    image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
    image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
  },
  {
    id: 18,
    title: "ASUS ROG Strix G17",
    category: "Gaming Laptop",
    price: "$1,300.00",
    rating: 5,
    tab: "Most-viewed products",
    rating: 5,
    discount: "-20%",
    image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
    image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
  },
  {
    id: 19,
    title: "ASUS ROG Strix G17",
    category: "Gaming Laptop",
    rating: 5,
    tab: "Most-viewed products",
    price: "$1,300.00",
    rating: 5,
    discount: "-20%",
    image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
    image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
  },
  {
    id: 20,
    title: "ASUS ROG Strix G17",
    rating: 5,
    tab: "Most-viewed products",
    category: "Gaming Laptop",
    price: "$1,300.00",
    rating: 5,
    discount: "-20%",
    image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
    image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
  },

  {
    id: 21,
    title: "Apple Mac mini M1",
    category: "Office PCs",
    rating: 5,
    tab: "Most-viewed products",
    price: "$699.00",
    rating: 4,
    image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
    image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
  },
  {
    id: 22,
    title: "Apple Mac mini M1",
    rating: 5,
    tab: "Most-viewed products",
    category: "Office PCs",
    price: "$699.00",
    rating: 4,
    image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
    image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
  },
  {
    id: 23,
    title: "Apple iPad Wi-Fi",
    category: "Apple Ipad",
    rating: 5,
    tab: "Most-viewed products",
    price: "$450.00",
    rating: 4.5,
    image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
    image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
  },
  {
    id: 24,
    title: "Apple Mac mini M1",
    category: "Office PCs",
    rating: 5,
    tab: "Most-viewed products",
    price: "$699.00",
    rating: 4,
    image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
    image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
  },
  {
    id: 25,
    title: "Apple Mac mini M1",
    category: "Office PCs",
    price: "$699.00",
    rating: 5,
    tab: "Most-viewed products",
    rating: 4,
    image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
    image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
  },
  {
    id: 26,
    title: "Apple Mac mini M1",
    category: "Office PCs",
    price: "$699.00",
    rating: 5,
    tab: "Most-viewed products",
    rating: 4,
    image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
    image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
  },
  {
    id: 27,
    title: "Apple Mac mini M1",
    category: "Office PCs",
    rating: 5,
    tab: "Top selling",
    price: "$699.00",
    rating: 4,
    image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
    image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
  },
  {
    id: 28,
    title: "Apple Mac mini M1",
    category: "Office PCs",
    tab: "Top selling",
    price: "$699.00",
    rating: 4,
    image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
    image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
  },
  {
    id: 29,
    title: "Apple Mac mini M1",
    category: "Office PCs",
    price: "$699.00",
    tab: "Top selling",
    rating: 4,
    image: "/assets/images/apple-iphone-14-plus-blue-2.jpg",
    image2: "/assets/images/apple-iphone-14-plus-blue-1.jpg",
  },
];
